=encoding utf-8

=head0 *Preface

Dogecoin is the Internet's original meme-based cryptocurrency.

That sentence may read like a bunch of nerdy nonsense to you. Don't worry; it
is! Fortunately, this book will make it clearer. It'll still be a bunch of
nerdy nonsense, but you'll understand it and be able to have fun, do cool
things, and show off your new knowledge to friends at partiesN<Talk about other
things too; we want you invited I<back>.>.

Let's explain that first sentence.

Dogecoin is what we're talking about.

The Internet is a globally-distributed network of computers that lets people
and machines communicate in words, pictures, video, audio, and all kinds of
data.

X<meme>

A meme is an idea, usually clever or ironic or sarcastic or joking, that's
easily spread between people. It often takes the form of an image or video that
can be shared on the Internet.

X<cryptocurrency>

Cryptocurrency is a mechanism to record digital transactions over the Internet
between people who don't necessarily trust each other as individuals but, as a
group, agree to specific ways to communicate that ideally make the entire
network of people trustworthy enough to serve as a mechanism of financial
exchange.

Whew.

The crypto stuff is interesting, and there's a lot to learn if you want, but
most of it summarizes to this: you don't have to take someone's word that
they're trustworthy. You should be able to verify it.

If that sounds like a lot of work with a bunch of serious nerds doing serious
nerd stuff, remember that there's a friendly dog mascot with a bunch of silly
memes and the whole point is to have fun.

That's what this book is about.

=begin sidebar What do I need?

This book assumes you have access to a computer somewhere (though some of the
tricks will work on mobile devices such as phones and tablets), have access to
the Internet, and can download and install and run software.

X<Dogecoin Core; trustworthy links>

At the time of this writing, you can visit U<dogecoin.com> for links and
information about how to download and run the Dogecoin Core. Don't take our
word for it though; check online if that's still the home of the Core. Test
that against other sites such as U<https://github.com/dogecoin/dogecoin>, the
Dogecoin Reddit at U<https://reddit.com/r/dogecoin/> and other locations.  If
something seems off to you, then ask questions. Honest, helpful people will
give you good answers and help you verify them for yourself.

=end sidebar

=head1 *How to Read This Book

A cryptocurrency with a friendly dog mascot is supposed to be I<fun>, so you
should read this book in a way that you enjoy. Maybe that's front to back or
back to front or skipping around. Maybe you read a couple of pages before going
to sleep to relax you or teach your brain a lesson. The only I<wrong> way to
read this book is a way that you don't enjoy.

In general, the book starts by assuming you're new to cryptography,
cryptocurrency, and Dogecoin. Earlier pages introduce concepts that later pages
build on, but it's totally okay to skip around. Skim the table of contents.
Look at the names of every chapter and every tip. If something grabs your
attention, read that first. Repeat.

This book also tries to express links between concepts, ideas, and tips.
Sometimes something introduced earlier will show up later, and sometimes you'll
see similar themes repeated throughout the book. That's on purpose. It's just
as valid to breeze through this book on a lazy summer afternoon as it is to
skim through it over the period of weeks, months, or years. Feel free to set it
down and come back to it later; all of the information will be waiting for you,
and ideally each tip has enough breadcrumbs to point to other places that you
can remind yourself where you were in your journey at the time.

Put this book on your bedside table. Face it out on from the bookshelf behind
you when you're on video calls. Carry it when you're walking, riding the train,
or enjoying a cannolo from a park bench downtown. Lend a copy to your friends
and donate a copy to your local library. Above all, embrace the fun. Your
author believes that learning things can be enjoyable and being in control of
your own coins is liberating and powerful. There's a lot to learn, but it
doesn't have to be intimidating. It can be fun and playful.

With that said, take note of a couple of things.

=head2 *Cryptocurrency Isn't Only Dogecoin

Although this book I<focuses> on Dogecoin, the basic concepts and a lot of the
ideas apply to multiple cryptocurrencies, especially Litecoin and Bitcoin. Many
of the examples will work with small or minor modifications. If you prefer one
of those other coins over Dogecoin, that's totally okay! You can still learn a
lot and have the appropriate amount of fun. We all share some common ground,
including code, so we can all learn from each other.

=head2 *Programmable Money Brings Risks

Even if the only thing we used cryptocurrency for were to track scores in a
massive, multiplayer online game of some kind, there would still be risks. The
fact that it's I<money> means those risks are more serious. Scammers, thieves,
grifters, and other bad actors are, unfortunately, a part of the landscape.
Where possible, this book attempts to identify risks to you, the people you
care about, and the other people in the community. It's up to you to keep
yourself and other people safe, but it's only possible to ameliorate risks you
know about. Read the risk sections carefully and think about other things that
could go wrong.

If you're not sure, ask. After you ask, verify. After all, this is a book about
ways to prove things. Knowledge is power.

=head2 *A Little Programming Can Be Fun

There's code in this book, and if you're familiar with programming in a
language such as Python, Ruby, JavaScript, Perl, or something else, you're in a
position to get the most out of it. If you've never done this before, that's
okay too! The code is there to help you understand and take advantage of
things, but you don't have to be a programmer to use programmable money
effectively.

With that said, you will get the most out of this book if you're comfortable
installing and configuring software, especially working with text files and the
command line. If you have a trusted friend to help you, you can learn a lot and
take control of your system in ways you previously didn't understand.

Basically if you're comfortable working a spreadsheet, you can build up your
skills!

=head2 *You Can Grow with This Book

Sure, you picked up this book because it has cute dogs on the cover and you're
not yet ready to build a pinball museum where people pay for credits with
cryptocurrency. That's okay! If you read one tip today and another every week
after that, you'll get through this book in two years. That's not a bad
investment of lazy Sunday afternoons--and at that point, you may be full of
other ideas no one has thought of before as well as new skills to bring them to
life.

=head1 *Credits

This work, as expected, has turned out to have required the assistance of many
people.

X<people; RNB>
X<people; meta_rach>
X<people; mishaboar>
X<people; Patrick Lodder>

Thank you to RNBN<U<https://twitter.com/RNB333>> and
RachelN<U<https://twitter.com/meta_rach>> for editorial questions and
suggestions which led to several of these tips!

Thank you to MishaboarN<U<https://twitter.com/Mishaboar>> for advice,
perspective, and helping promote a deep empathy for other people--as well as the lovely foreword!

Thank you to Patrick LodderN<U<https://github.com/patricklodder/>> for technical
advice and always-trenchant corrections.

Any remaining errors are the fault of the sometimes-too-clever author.
