=head1 Launch the Core Silently

Z<launch_core_silently>

Think back to the first time you launched the Dogecoin Core on your computer. A
friendly dog's face popped up along with some text in a cartoonish font, as if
to say "Don't worry. Things are happening, but it'll be okay. Don't take it all
so seriously. We're going to have fun and learn some things."

All of that is true, but if you've set up your Core to launch when you launch
your computer (or if you launch it yourself to run in the background), you
might not need that window to pop up every time.

We can make things quieter, of course.

=head2 *Minimize Splashing and Windows

This happy little window is called a "splash screen", both in application
parlance and in the Dogecoin source code itself. Now that you know that, you
know almost everything you need to make the Core launch itself a little more
quietly.

If you run C<dogecoin-qt> yourself from a command line, you might have used the
C<--help> command to show a list of options you can use to change how the Qt
GUI works. Here we care about two (other output elided for the sake of this
example):

=begin screen

  $ B<dogecoin-qt --help>
  ...
  UI Options:

    -min
         Start minimized

    -splash
         Show splash screen on startup (default: 1)

=end screen

In other words, if you launch the Core with C<--splash=0> and C<-min>, you'll
see no splash screen and, when the program finishes validating the blockchain
and loading your wallet, you won't see the main window either. The program will
simply run in the background and do its thing until you ask to see it.

If you're using a Unix-like system such as Linux, a BSD, or Mac OS X and launch
the program yourself from the command lineN<You can do this from Windows as
well, of course.>, you can write a shell script, set an alias, or simply type
C<dogecoin-qt -splash=0 -min> and not much will (visibly) happen.

If you use the GUI to launch the Core, you'll have to find the launcher and
change its properties to pass these command-line options.

=for author

Figure out how to fill this in.

=head2 *Understand the Risks

The biggest risk to changing how you launch the Core is that you might forget
it's started and leave it running. Yes, the happy little Doge icon will still
be in your system tray, but if you don't see the splash screen or have the main
window pop up when everything starts, everything your Core is configured to do
could be running without you knowing it.

That list of I<everything> includes sending and receiving network traffic,
updating your wallet, and responding to RPC requests. Even if you're certain
this isn't an issue, double- and triple-check before you let anything launch
your Core without you knowing exactly when and how it's running.

=end for
